/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Video = IDL.Record({
  'tag' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'addVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Video], []),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Video = IDL.Record({
    'tag' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  
  return IDL.Service({
    'addVideo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Video], []),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };